name: test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: check-out
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '8.0.232'
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.10.1.763'
      - uses: actions/setup-node@v2
        with:
          node-version: '12.19.0'
      - name: deps
        run: make deps
      - name: env-file
        run: |
          echo "NUID_AUTH_API_KEY=${{ secrets.NUID_AUTH_API_KEY }}" > .env
          echo "NUID_AUTH_API_HOST=${{ secrets.NUID_AUTH_API_HOST }}" >> .env
          cat .env
      - name: test
        run: make test
